### ISSUE TITLE
Buggy stats screen, skips days 

### ISSUE THREAD

**Issue by homerjunior** [isaakhanimann/psychonautwiki-journal-android#41] opened 2024-01-31 05:37 UTC
I have recorded everyday since the 4th January but as you can see it has gaps in the month timeline, recorded every day this week yet half are missing in weekly view![Screenshot_20240131-163625.png](https://github.com/isaakhanimann/psychonautwiki-journal-android/assets/131698580/391c2dc7-e373-4cb9-8bd7-ebe5b9383cc1)

![Screenshot_20240131-163621.png](https://github.com/isaakhanimann/psychonautwiki-journal-android/assets/131698580/84a14e3f-1caf-4692-823c-c1e58b4d96e1)

**Comment by isaakhanimann** [comment] 2024-01-31 06:58
Can you send me the export of your journal so I can see the specific times of the experiences and ingestions?
My username is @isaakhanimann on Telegram

**Comment by homerjunior** [comment] 2024-01-31 09:30
Could I grab an email? I don't use telegram

**Comment by isaakhanimann** [comment] 2024-01-31 10:25
Thank you. Sure here: retests.unarmed-0b@icloud.com

**Comment by jaromeyer** [comment] 2024-02-08 10:26
this is most likely expected behaviour. each "day" is not really a discrete day (date) but rather a span of 24 hours. so only if you are looking at the statistics at exactly midnight each column should correspond to a day. otherwise if you consumed twice during 24 hours the corresponding column will contain two experiences while the neighbouring ones might be empty. in you screenshot the experiences aren't "lost", they are just bunched up in every second 24 hour interval.

**Comment by homerjunior** [comment] 2024-02-21 20:50
Just put a gap of well over 24 hours and 30 day view shows no gap lol

**Comment by isaakhanimann** [comment] 2024-02-22 06:41
I can't reproduce this issue. The way the algorithm works is that it only looks at the sort date of the experience and assigns the whole experience to the day of the sort date. Even if other ingestions in the experience are on the next day.
The sort date is fixed as the time of ingestion when the experience is created. So if you were deleting ingestions and adding new ones at different days to the same experience the whole thing might be messed up.

**Comment by isaakhanimann** [comment] 2024-02-23 05:51
Actually the issue was maybe because it started from the current time and took 24 hour steps backwards. So I adjusted it to start from the current end of day and then moving back 24 hours. Fix is in the next update.

**Closed** 2024-02-23 14:51 UTC
